import type { Metadata } from "next";
import { Inter } from "next/font/google";

import {
  Bookmark,
  Mail,
  MoreHorizontal,
  ScrollText,
  Settings,
  User as UserImage,
  Users2,
  MailPlus,
} from "lucide-react";
import DropdownMenu from "@/components/User/DropdownMenu";
import Link from "next/link";
import { PublicUsers } from "@prisma/client";
import { getServerSession } from "next-auth";
import { authOptions } from "@/libs/authOptions";
import { redirect } from "next/navigation";
import React from "react";
import UserProfileChat from "@/components/User/UserProfileChat";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session: SessionWithExp | null = await getServerSession(authOptions);

  if (!session?.user || session?.exp < Date.now() / 1000) redirect("/sign-in");

  const user: PublicUsers | null | undefined =
    await prisma?.publicUsers.findUnique({
      where: { id: session?.user?.id },
    });

  const data = await prisma?.message.findMany({
    where: {
      OR: [
        {
          userOne_id: session?.user?.id,
        },
        {
          userTwo_id: session?.user?.id,
        },
      ],
    },
    include: {
      directMessage: true,
      userOne: true,
      userTwo: true,
    },
  });

  const messages: MessageWithUsers[] | undefined = data?.map((msg) => {
    const user =
      (msg.userTwo_id === session?.user?.id && msg.userOne) ||
      (msg.userOne_id === session?.user?.id && msg.userTwo);

    return {
      ...msg,
      user,
    };
  });

  return (
    <>
      <div className="w-full border-r border-zinc-600 max-w-[390px]  max-lg:max-w-[800px]">
        <header className="flex flex-row justify-between p-4 max-lg:hidden max-lg:opacity-0">
          <div>
            <h2 className="text-xl font-bold">Messages</h2>
          </div>
          <div className="flex flex-row gap-2">
            <Settings />
            <MailPlus />
          </div>
        </header>
        <main className="max-lg:hidden max-lg:opacity-0">
          <div className="p-4">
            <input
              placeholder="Search Direct Messages"
              type="search"
              className="bg-black w-full py-2 px-4 rounded-3xl border border-zinc-500 outline-none text-zinc-800 text-sm"
            />
          </div>
          <div>
            <UserProfileChat messages={messages} />
          </div>
        </main>
        <div className="lg:hidden max-w-[600px] mx-auto">{children}</div>
      </div>
      <main className="border-r border-zinc-600 flex max-w-[600px] w-full max-lg:hidden max-lg:opacity-0 ">
        {children}
      </main>
    </>
  );
}
