import { NextAuthProvider } from "@/components/providers/authProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ThemeProvider } from "@/components/providers/themeProvider";
import { SocketProvider } from "@/components/providers/socketProvider";
import ModalProvider from "@/components/providers/modalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className && `bg-black `}>
        <NextAuthProvider>
          <SocketProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <ModalProvider />
              {children}
            </ThemeProvider>
          </SocketProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
