import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import Image from "next/image";
import { redirect } from "next/navigation";
import Link from "next/link";
import { Posts, PublicUsers } from "@prisma/client";
import { authOptions } from "@/libs/authOptions";

import {
  ArrowLeft,
  Bookmark,
  CalendarDays,
  Mail,
  MoreHorizontal,
  ScrollText,
  User as UserImage,
  Users2,
} from "lucide-react";

import DropdownMenu from "@/components/User/DropdownMenu";

import noBackground from "@/public/no-image.png";
import noUser from "@/public/no-user-image-icon-23.jpg";
import UserLinks from "@/components/User/UserLinks";
import UserFollowButton from "@/components/User/UserFollowButton";
import UserChangeInfo from "@/components/User/UserChangeInfo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type UserWithPosts = PublicUsers & {
  posts: Posts[];
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { id: string };
}) {
  const session: SessionWithExp | null = await getServerSession(authOptions);

  if (!session?.user || session?.exp < Date.now() / 1000) redirect("/sign-in");

  const user: UserWithPosts | null | undefined =
    await prisma?.publicUsers.findUnique({
      where: { user_name: params.id },
      include: { posts: true },
    });

  return (
    <div className="min-h-full">
      <div className="max-w-[1200px] grid grid-cols-[0.6fr_1.7fr_0.7fr] mx-auto h-[100vh] max-h-[100vh]">
        <aside className="border-r border-zinc-600 h-screen pt-2 pb-5 flex justify-between flex-col">
          <div>
            <div className="px-4">
              <Link href="/" className="">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="icon icon-tabler icon-tabler-brand-twitter-filled"
                  width="40"
                  height="40"
                  viewBox="0 0 24 24"
                  strokeWidth="2"
                  stroke="currentColor"
                  fill="none"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                  <path
                    d="M14.058 3.41c-1.807 .767 -2.995 2.453 -3.056 4.38l-.002 .182l-.243 -.023c-2.392 -.269 -4.498 -1.512 -5.944 -3.531a1 1 0 0 0 -1.685 .092l-.097 .186l-.049 .099c-.719 1.485 -1.19 3.29 -1.017 5.203l.03 .273c.283 2.263 1.5 4.215 3.779 5.679l.173 .107l-.081 .043c-1.315 .663 -2.518 .952 -3.827 .9c-1.056 -.04 -1.446 1.372 -.518 1.878c3.598 1.961 7.461 2.566 10.792 1.6c4.06 -1.18 7.152 -4.223 8.335 -8.433l.127 -.495c.238 -.993 .372 -2.006 .401 -3.024l.003 -.332l.393 -.779l.44 -.862l.214 -.434l.118 -.247c.265 -.565 .456 -1.033 .574 -1.43l.014 -.056l.008 -.018c.22 -.593 -.166 -1.358 -.941 -1.358l-.122 .007a.997 .997 0 0 0 -.231 .057l-.086 .038a7.46 7.46 0 0 1 -.88 .36l-.356 .115l-.271 .08l-.772 .214c-1.336 -1.118 -3.144 -1.254 -5.012 -.554l-.211 .084z"
                    strokeWidth="0"
                    fill="currentColor"
                  ></path>
                </svg>
              </Link>
            </div>
            <ul className="mt-2">
              <li>
                <Link
                  href="/"
                  className="flex flex-row gap-4 hover:bg-zinc-800 w-max px-4 py-3 rounded-3xl"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    className="lucide lucide-home font-bold text-xl text-white"
                  >
                    <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
                    <polyline points="9 22 9 12 15 12 15 22" />
                  </svg>
                  <span className="text-white font-bold text-xl">Home</span>
                </Link>
              </li>
              <li>
                <Link
                  href="?explore=true"
                  className="flex flex-row gap-4 hover:bg-zinc-800 w-max px-4 py-3 rounded-3xl"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="icon icon-tabler icon-tabler-search"
                    width="26"
                    height="26"
                    viewBox="0 0 24 24"
                    strokeWidth="2"
                    stroke="currentColor"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"></path>
                    <path d="M21 21l-6 -6"></path>
                  </svg>
                  <span className="text-white text-xl">Explore</span>
                </Link>
              </li>
              <li>
                <Link
                  href="/"
                  className="flex flex-row gap-4 hover:bg-zinc-800 w-max px-4 py-3 rounded-3xl"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="icon icon-tabler icon-tabler-bell"
                    width="26"
                    height="26"
                    viewBox="0 0 24 24"
                    strokeWidth="2"
                    stroke="currentColor"
                    fill="none"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <path d="M10 5a2 2 0 1 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6"></path>
                    <path d="M9 17v1a3 3 0 0 0 6 0v-1"></path>
                  </svg>
                  <span className="text-white text-xl">Notifications</span>
                </Link>
              </li>
              <li>
                <Link
                  href="/messages"
                  className="flex flex-row gap-4 hover:bg-zinc-800 w-max px-4 py-3 rounded-3xl"
                >
                  <Mail />
                  <span className="text-white text-xl">Messages</span>
                </Link>
              </li>
              <li>
                <Link
                  href={"/"}
                  className="flex flex-row gap-4 hover:bg-zinc-800 w-max px-4 py-3 rounded-3xl"
                >
                  <ScrollText />
                  <span className="text-white text-xl">Lists</span>
                </Link>
              </li>
              <li>
                <Link
                  href={"/"}
                  className="flex flex-row gap-4 hover:bg-zinc-800 w-max px-4 py-3 rounded-3xl"
                >
                  <Bookmark fill="true" />
                  <span className="text-white text-xl">Bookmarks</span>
                </Link>
              </li>
              <li>
                <Link
                  href={"/"}
                  className="flex flex-row gap-4 hover:bg-zinc-800 w-max px-4 py-3 rounded-3xl"
                >
                  <Users2 />
                  <span className="text-white text-xl">Communities</span>
                </Link>
              </li>
              <li>
                <Link
                  href={"/"}
                  className="flex flex-row gap-4 hover:bg-zinc-800 w-max px-4 py-3 rounded-3xl"
                >
                  <UserImage />
                  <span className="text-white text-xl">Profile</span>
                </Link>
              </li>

              <li>
                <Link
                  href={"/"}
                  className="flex flex-row gap-4 hover:bg-zinc-800 w-max px-4 py-3 rounded-3xl"
                >
                  <MoreHorizontal />
                  <span className="text-white text-xl">More</span>
                </Link>
              </li>
              <li className="mt-5">
                <Link href={"/post/create"}>
                  <button className="bg-primary text-white font-bold text-xl bg-sky-600 rounded-full px-20 py-3 w-max">
                    Post
                  </button>
                </Link>
              </li>
            </ul>
          </div>
          <div className="flex items-end">
            <DropdownMenu publicUser={user} />
          </div>
        </aside>
        <main>
          <header className="border-b border-zinc-600">
            <div className="flex flex-row px-4 py-1 items-center gap-8 sticky top-0 backdrop-blur-lg backdrop-saturate-[37%] bg-[rgba(0,0,0,0.64)]  z-30">
              <Link href="/">
                <ArrowLeft width={18} />
              </Link>
              <div className="flex flex-col">
                <h2 className="text-xl text-white font-bold">{user?.name}</h2>
                <span className="text-sm text-zinc-500">
                  {user?.posts?.length} posts
                </span>
              </div>
            </div>
            <div>
              <Image
                src={noBackground}
                className="max-w-[100%] h-auto block"
                width={1920}
                height={1080}
                alt=""
              />
            </div>
            <div className="ml-4 flex flex-row h-20 justify-between">
              <div>
                <Image
                  src={user?.image || noUser}
                  width={600}
                  height={600}
                  className="w-[100px] relative top-[-50px] rounded-full border-3 border-[#1c1c1c] sm:w-[140px] sm:top-[-70px]"
                  alt=""
                />
              </div>
              <div>
                {user && user.id === session.user.id ? (
                  <UserChangeInfo id={session.user.id} />
                ) : (
                  <UserFollowButton
                    id={session?.user?.id}
                    otherUserId={user?.id}
                  />
                )}
              </div>
            </div>
            <div className="px-4">
              <div className="flex flex-col py-2">
                <h2 className="text-white font-bold w-max text-xl cursor-pointer hover:underline">
                  {user?.name}
                </h2>
                <span className="text-zinc-500 block text-sm cursor-pointer">
                  @{user?.user_name}
                </span>
              </div>
              <div>
                <span className="text-[#e7e9ea] text-sm">{user?.bio}</span>
              </div>
              <div className="flex flex-row mt-2 text-zinc-500  text-sm gap-2 items-center">
                <CalendarDays width={18} />
                <span>
                  Se unio en{" "}
                  {new Date(user ? user?.createdAt : "").toLocaleDateString()}
                </span>
              </div>
              <div className="flex flex-row gap-2 mt-2 text-sm">
                <span className="flex flex-row gap-1 cursor-pointer hover:underline font-extralight">
                  <strong className="text-white font-bold block text-md">
                    0
                  </strong>
                  Siguiendo
                </span>
                <span className="ml-2 flex flex-row gap-1 cursor-pointer hover:underline font-extralight">
                  <strong className="text-white font-bold block text-md">
                    12
                  </strong>
                  Seguidores
                </span>
              </div>
            </div>
            <div className="mt-4">
              <UserLinks user={user} />
            </div>
          </header>
          <section>{children}</section>
        </main>
        <aside className="border-l border-zinc-600 h-screen"></aside>
      </div>
    </div>
  );
}
